version: '3'

networks:
  hank-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

services:
  go_api:
    image: golang:1.11.2-alpine3.8
    container_name: go_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../go:/go
    ports:
      - 3001:8080
    working_dir: /go/src
    depends_on:
      - couchdb
    command: >
      bash -c "go mod tidy&&
       fresh"
    tty:
      true
  couchdb:
    image: couchdb:2
    restart: always
    container_name: couchdb
    networks:
      hank-net:
        ipv4_address: 192.168.200.10
    ports:
      - 5984:5984
    volumes:
      - ../data:/opt/couchdb/data
    environment:
      COUCHDB_PASSWORD: admin
      COUCHDB_USER: admin
